sonar.projectKey=CHANGE_ME_PROJECT_KEY
sonar.projectName=aws-batch-streaming-skeleton
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=tests/**
sonar.qualitygate.wait=true
